### PR TITLE
Migrate from drools version 7.0.0.Final to 7.51.0.Final

### PR DESCRIPTION
**Pull request by al-filippov**
Try to fix warning -- WARNING: An illegal reflective access operation has occurred

Migrate from drools version 7.0.0.Final to 7.51.0.Final

### CODE REVIEW

**Comment by martinjoconnor** [comment]
Thanks. I'm on vacation at the moment. I will take a look at this next week.

**Comment by al-filippov** [comment]
@martinjoconnor, what about my PR?

**Comment by martinjoconnor** [comment]
Looking at this now and it seems to work. Thanks for doing this - and apologies for taking so long to get to it.

I will get a new release out today if everything works.

**Comment by al-filippov** [comment]
Thank you for the good news! I hope for further cooperation =)

**Comment by martinjoconnor** [comment]
I have made a new 2.0.10 release of the SWRLAPI components using your pull request (actually bumped to 7.57.0.Final).

Thanks again for the contribution.

**Pull request merged**
