### PR TITLE
Migrate from drools version 7.0.0.Final to 7.51.0.Final

### PR DESCRIPTION
**Pull request by al-filippov**
Try to fix warning -- WARNING: An illegal reflective access operation has occurred

### CODE REVIEW

**Comment by martinjoconnor** [comment]
Sorry for not looking at this earlier. I have been busy with other projects. I will take a look at this tomorrow. 

Do all the integration tests in https://github.com/protegeproject/swrlapi-integration-tests pass with this update?

Martin

**Comment by martinjoconnor** [comment]
I tried this but all the integration tests in the  https://github.com/protegeproject/swrlapi-integration-tests project failed.

**Comment by al-filippov** [comment]
The tests are working strangely.
Original (not modified, without my changes) project fails tests in Linux due to ConcurrentModificationException in random parts of tests. If I trying to run tests again in Linux the ConcurrentModificationException has also been throw in random parts of tests.
The original project also fail tests on Windows due to NillPointerException. But if I try to run the command `mvn clean install` in Windows again tests passed successfully.
All tests were run on clean operating systems with openjdk-8.

**Comment by al-filippov** [comment]
The tests give the same results for the modified project.
Logs in the attachment.
[test-logs-swrlapi-modified-windows.zip](https://github.com/protegeproject/swrlapi-drools-engine/files/6247772/test-logs-swrlapi-modified-windows.zip)
[test-logs-swrlapi-modified-linux.zip](https://github.com/protegeproject/swrlapi-drools-engine/files/6247773/test-logs-swrlapi-modified-linux.zip)

**Comment by al-filippov** [comment]
Most likely the problem with ConcurrentModificationException arises in the owlapi library.

See stacktrace.
```
Expected: (an instance of org.swrlapi.parser.SWRLParseException and exception with message a string containing "literal value 'x42' is not a valid http://www.w3.org/2001/XMLSchema#int")
     but: an instance of org.swrlapi.parser.SWRLParseException <java.util.ConcurrentModificationException> is a java.util.ConcurrentModificationException
Stacktrace was: java.util.ConcurrentModificationException
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1390)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at org.semanticweb.owlapi.utilities.Injector.inject(Injector.java:205)
	at org.semanticweb.owlapi.apibinding.OWLManager.createOWLOntologyManager(OWLManager.java:114)
	at org.swrlapi.SWRLCoreNumericIT.TestSWRLCoreNumericInvalidIntLiteral(SWRLCoreNumericIT.java:310)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:405)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by martinjoconnor** [comment]
Sorry for the delay in getting back to you - have been busy with other projects.

I had to try to manually try your pull request because I did not want to modify the master branch. (The master branch is never modified directly and is generally only touched by the release process when releasing to Maven central.)

Can you do a pull request against a new feature branch that you create?

**Comment by al-filippov** [comment]
Do you mean what I must to make the pull request in the development branch instead of the master branch?

**Comment by martinjoconnor** [comment]
On a feature branch:

https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow

**Comment by al-filippov** [comment]
In pull request creation I can use the only master and develop branches. I don't have permission to create a new branch in the original repo.

image

**Comment by martinjoconnor** [comment]
Ok - I have made sure my develop branch is clean. You can create a pull request against that. 

Thanks.

**Comment by al-filippov** [comment]
https://github.com/protegeproject/swrlapi-drools-engine/pull/13

**Comment by martinjoconnor** [comment]
Merged later version of this pull request (https://github.com/protegeproject/swrlapi-drools-engine/pull/13)

**Pull request closed without merging**
